language: ruby

sudo: false

rvm:
  - 1.9.3
  - jruby
  - 2.0.0
  - 2.1.0

matrix:
  allow_failures:
    - rvm: jruby

env:
  - LOB_API_KEY=test_0dc8d51e0acffcb1880e0f19c79b2f5b0cc

before_script:
  - bundle exec rake dev:setup
  - rm -rf spec/vcr_cassettes

script: bundle exec rake test
